# Project information
site_name: Quantify RNA localization in liver
site_description: Collection of post-processing scripts for images analyzed with FISH-quant,
site_author: Florian MUELLER
site_url: https://muellerflorian.github.io/walesky-rna-loc-liver/

# Repository
repo_name: GitHub
repo_url: https://github.com/muellerflorian/walesky-rna-loc-liver.git
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2019 Florian MUELLER'

# Configuration
theme:
  name: 'material'
  #name: mkdocs
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /img/icons8-eukaryotic-cells-filled-100.png
  logo:
    icon: wb_sunny

# Customization
extra:
  social:
    - type: github-alt
      link: https://github.com/muellerflorian
    - type: linkedin
      link: https://www.linkedin.com/in/muellerflorian/
    - type: google
      link: https://scholar.google.fr/citations?user=WrEj9t4AAAAJ

# MD extension
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tilde
  - attr_list

nav:
    - Overview: index.md   # Needed for material theme but not for other
    - ImJoy: tools-imjoy.md
    - Jupyter: tools-jupyter.md  # This is strange but only with this organization this file shows upd in the overview together with the index.md

    - General workflows:
      - RNA detection with FQ: rna-detection.md
      - Image annotation with ImJoy: imjoy-annotation.md

    - Analysis workflows:
      - Expression gradient: expression-gradient.md
      - Cell environment: cell-environment.md

    - About:
      - Licence: licence.md


#theme:
#  name: 'material'
